apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: mzabolotnov/shop_frontend:1.0
    name: frontend
    resources: {}
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: 1.1.1.1
    - name: CURRENCY_SERVICE_ADDR
      value: 2.2.2.2
    - name: CART_SERVICE_ADDR
      value: 1.1.1.1
    - name: RECOMMENDATION_SERVICE_ADDR
      value: 1.1.1.1
    - name: CHECKOUT_SERVICE_ADDR
      value: 1.1.1.1
    - name: SHIPPING_SERVICE_ADDR
      value: 1.1.1.1
    - name: AD_SERVICE_ADDR
      value: 1.1.1.1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
