apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web # Название Pod
 labels: # Метки в формате key: value
  key: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: web
  #  image: thatsme/web:1.2
#  - name: co-ex-nginx
   image: mzabolotnov/ex_nginx:1.0
   livenessProbe:
    tcpSocket: { port: 8000 }
   readinessProbe: # Добавим проверку готовности
    httpGet: # веб-сервера отдавать
     path: /index.html # контент
     port: 8000
   volumeMounts:
   - name: app
     mountPath: /app
 initContainers:
 - name: init-ex-nginx
   image: busybox:1.31.0
   command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
   volumeMounts:
   - name: app
     mountPath: /app
 volumes:
 - name: app
   emptyDir: {}
